export const typeHistory = [
  "Contos de Fadas",
  "Ficção Científica",
  "Fantasia Épica",
  "Mistério",
  "Romance",
  "Aventura",
  "História de Amadurecimento (Coming-of-Age)",
  "Terror",
  "Comédia",
  "Drama",
  "Histórias de Vida",
  "Histórias de Viagem no Tempo",
  "Histórias de Super-heróis",
  "Histórias de Amizade",
  "Histórias Históricas",
  "Mitologia",
  "Contos de Ficção Científica",
  "Histórias de Suspense",
  "Fábulas",
  "Histórias de Redenção",
  "Histórias de Guerra",
  "Histórias de Natureza e Aventura",
  "Distopia",
  "Contos de Viagem",
  "Histórias de Família",
  "Contos Filosóficos",
  "Histórias de Justiça",
  "Histórias de Ficção Científica Social",
  "Histórias de Aprendizado",
  "Histórias de Magia",
];
