export const typeMissions = [
  "Apollo 11",
  "Voyager 1 e Voyager 2",
  "Hubble Space Telescope (Telescópio Espacial Hubble)",
  "Mars Rover (várias missões, incluindo Curiosity e Perseverance)",
  "Cassini-Huygens",
  "New Horizons (Nova Fronteira)",
  "Apollo 13",
  "Viking (1 e 2)",
  "Skylab",
  "Pioneer (várias missões)",
  "Gemini (várias missões)",
  "Space Shuttle (várias missões do Ônibus Espacial)",
  "Magellan",
  "Galileo",
  "Juno",
  "InSight",
  "Mars Science Laboratory (Laboratório de Ciências de Marte)",
];
